$primary = rgb(b5d07f)
$surface = rgb(12140f)
$secondary = rgb(c0cba5)
$error = rgb(ffb4ab)
$tertiary = rgb(89d7ae)
$surface_lowest = rgb(0d0f0a)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
